export default {
  title: 'ligth',
  colors: {
    colorBackground: '#F0F0F7',
    colorPrimarylighter: '#9871F5',
    colorPrimarylight: '#916BEA',
    colorPrimary: '#8257E5',
    colorPrimarydark: '#774DD6',
    colorPrimarydarker: '#6842C2',
    colorSecundary: '#04D361',
    colorSecundarydark: '#04BF58',
    colorTitleinprimary: '#FFFFFF',
    colorTextinprimary: '#D4C2FF',
    colorTexttitle: '#32264D',
    colorTextcomplement: '#9C98A6',
    colorTextbase: '#6A6180',
    colorLineinwhite: '#E6E6F0',
    colorInputbackground: '#F8F8FC',
    colorButtontext: '#FFFFFF',
    colorBoxbase: '#FFFFFF',
    colorBoxfooter: '#FAFAFC',
    colorTextspan: '#C1BCCC',
    colorTextspanerror: '#e34439',
  },
  fonts: {
    fontprimary: '#Archivo',
    fontsecondary: '#Poppins',
  },
};
